dist: bionic
language: python
python: 3.7

install:
# 安装最新的hugo nuo主题需要extended版本的hugo
  - wget -qO- https://api.github.com/repos/gohugoio/hugo/releases/latest | grep hugo_extended |sed -r -n '/browser_download_url/{/Linux-64bit.deb/{s@[^:]*:[[:space:]]*"([^"]*)".*@\1@g;p;q}}' | xargs wget
  - sudo dpkg -i hugo*.deb

script:
# 运行hugo命令
  - hugo

# 构建完成后会自动更新Github Pages
deploy:
  provider: pages # 重要，指定这是一份github pages的部署配置
  skip-cleanup: true # 重要，不能省略
  local-dir: public # 静态站点文件所在目录
  target-branch: master # 要将静态站点文件发布到哪个分支，默认gh-pages
  github-token: $GITHUB_TOKEN # 重要，$GITHUB_TOKEN是变量，需要在GitHub上申请、再到配置到Travis
  keep-history: true
  on:
    branch: source # 博客源码的分支