dist: bionic
language: python # 默认是ruby
python: 3.7

install:
  # nuo主题需要extended版本的hugo，其他主题可以用最新的就行
  # - wget -qO- https://api.github.com/repos/gohugoio/hugo/releases/latest | grep hugo_extended |sed -r -n '/browser_download_url/{/Linux-64bit.deb/{s@[^:]*:[[:space:]]*"([^"]*)".*@\1@g;p;q}}' | xargs wget
  - wget https://github.com/gohugoio/hugo/releases/download/v0.58.3/hugo_extended_0.58.3_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb

script:
  - hugo

# 构建成功后发一份到Coding Pages
after_success:
  - cd ./public
  - git init
  - git config user.name "opso"
  - git config user.email "945206413@qq.com"
  - git add .
  - git commit -m ":construction_worker: 自动部署"
  - git push --force --quiet "https://opso:${CODING_TOKEN}@git.dev.tencent.com/opso/opso.git" master:master

# 构建完成后会自动更新Github Pages
# 详见 https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  skip-cleanup: true
  local-dir: public
  target-branch: master
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: source