baseURL = ""
languageCode = "en"
title = "opso's blog"
theme = "nuo"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true
enableEmoji = true

# Disqus Username
# disqusShortname = ""

# Google Analytics UA number
# googleAnalytics = "UA-XXXXXXXX-X"

# Copyright of your post
copyright = "© This post is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License，please give source if you wish to quote or reproduce."

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

# [[menu.main]]
#   name = "Code"
#   weight = 20
#   identifier = "code"
#   url = "https://github.com/opso-code"

[[menu.main]]
  name = "Tags"
  weight = 20
  identifier = "tags"
  url = "/tags/"

# Add your own params here
[params]
  author = "opso"
  bg = "images/grey-prism.svg"
  avatar = "images/avatar.png"
  seotitle = "opso's blog"
  subtitle = ""
  description = "opso的技术博客"
  paginate = 20

  # Choose your social networks
  email = "945206413@qq.com"
  github = "opso-code"
  instagram = "opso92"
  # weibo = "weibo_username"
  # twitter = "twitter_username"
  # linkedin = "linkedin_username"
  # wechat= "images/qrcode.jpg"  # Replace with your wechat qrcode image

  Gitment = true
  GitmentOwner = "opso-code"
  GitmentRepo = "opso-code.github.io"
  GitmentClientId = "49e019d3a542f81b2c64"
  GitmentClientSecret = "dc3ad86113e35cd1335ca5d52e313e13829730ea"

  # Baidu Tongji (China Only)
  # https://tongji.baidu.com/
  baiduTongji = "f4b4545fe62e6e3a4f63e68324f24c95"
